### ISSUE TITLE
Instant closure upon excuting

### ISSUE THREAD

**Issue by JKW301** [missyaria/test#2]
**Describe the bug**
When I execute the program, a window opens and suddenly closes.
I suggest you add a line of code to prevent that bug and to add a "close window" function.

**To Reproduce**
1. Go to '/test'
2. Click on 'ls.py'
3. Scroll down to 'line4'

**Expected behavior**
I exepected a terminal

**Screenshots**

**Desktop (please complete the following information):**
 - WINDOWS 11:

**Comment by missyaria** [comment]
Thank you ! 
I updated the executable file so the windows closes only upon pressing the enter key, that way it doesn't instantly closes and you actually get to see the output. 
Fixed.
